spring:
  application:
    name: museum
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/museum
    username: museum
    password: museum123!@#
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      indent_output: true
auth:
  jwt:
    secret: oIl6/4nURBUCp7sR40hCUEO82z0VN4CAFbYix6RiReE=
logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: myapp.log
    path: C:/Users/meteo/Desktop/museum_mgtu
server:
  port: 8081
backup:
  path: C:/Users/meteo/Desktop/museum_mgtu
  dbName: museum