version: '3.3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: museum123!@#
      POSTGRES_USER: museum
      POSTGRES_DB: museum
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
  dokuwiki:
    image: dokuwiki/dokuwiki:stable # other tags: master, <date> or <codename>
    user: "1000:1000" # adjust to your required user id
    restart: unless-stopped
    ports:
      - "8081:8081" # internal port is 8080, map to what you need
    environment:
      PHP_TIMEZONE: Europe/Berlin
      #PHP_MEMORYLIMIT: 256M
      #PHP_UPLOADLIMIT: 128M
    volumes:
      - ./storage:/storage
volumes:
  pgdata:
