create database museum
    with owner museum;

create sequence public.exhibition_exhibit_seq
    increment by 50;

alter sequence public.exhibition_exhibit_seq owner to museum;

create sequence public.exhibition_seq
    increment by 50;

alter sequence public.exhibition_seq owner to museum;

create sequence public.shelf_seq
    increment by 50;

alter sequence public.shelf_seq owner to museum;

create sequence public.shelving_seq
    increment by 50;

alter sequence public.shelving_seq owner to museum;

create sequence public.storages_seq
    increment by 50;

alter sequence public.storages_seq owner to museum;

create table public.storages
(
    id      integer generated by default as identity
        primary key,
    address text not null
);

alter table public.storages
    owner to museum;

create table public.rooms
(
    id         integer generated by default as identity
        primary key,
    number     integer not null,
    storage_id integer not null
        constraint fkaqkscv2htoyh1ttkadk14xxpg
            references public.storages
);

alter table public.rooms
    owner to museum;

create table public.exhibition
(
    id          integer generated by default as identity
        primary key,
    date_from   timestamp(6) not null,
    date_to     timestamp(6) not null,
    description text         not null,
    name        varchar(256) not null
);

alter table public.exhibition
    owner to museum;

create table public.shelving
(
    id            integer generated by default as identity
        primary key,
    number        integer     not null,
    type          varchar(16) not null,
    exhibition_id integer
        constraint fkh3rue280m6lmi6i8vo51cpxid
            references public.exhibition,
    room_id       integer
        constraint fkesk8o957c9b6s0c9xctb8a0vv
            references public.rooms
);

alter table public.shelving
    owner to museum;

create table public.shelf
(
    id          integer generated by default as identity
        primary key,
    number      integer not null,
    shelving_id integer not null
        constraint fkmfum4qohpj3o7ijeh28fu7awg
            references public.shelving
);

alter table public.shelf
    owner to museum;

create table public.exhibit
(
    id               integer generated by default as identity
        primary key,
    name             varchar(256) not null,
    packaging_type   varchar(64),
    storage_shelf_id integer      not null
        constraint fk33j75ttp8msukvxvjcclk1g6v
            references public.shelf
);

alter table public.exhibit
    owner to museum;

create table public.exhibit_description
(
    id          integer generated by default as identity
        primary key,
    exhibit_id  integer      not null
        constraint fkbful2dheefwvugsts2p1d9luj
            references public.exhibit,
    description varchar(255) not null
);

alter table public.exhibit_description
    owner to museum;

create table public.exhibition_exhibit
(
    id             integer generated by default as identity
        primary key,
    description_id integer not null
        constraint fkrkicxw32b1pl4fqf5ftg2dre3
            references public.exhibit_description,
    exhibit_id     integer not null
        constraint fkap3tjj73yctux3j9lu2m224ga
            references public.exhibit,
    exhibition_id  integer not null
        constraint fkbuyyrjkj4r2f6tgicmv8a4xw9
            references public.exhibition,
    shelf_id       integer not null
        constraint fkhj6r43j342wtmqerapkjgm1hw
            references public.shelf
);

alter table public.exhibition_exhibit
    owner to museum;

create table public."user"
(
    id          integer generated by default as identity
        constraint pk_user
            primary key,
    name        varchar(64) not null,
    middle_name varchar(64),
    last_name   varchar(64) not null,
    role        varchar(256),
    secret      text        not null,
    username    varchar(128) default 'user'::character varying
);

alter table public."user"
    owner to museum;

INSERT into "user"(name, middle_name, last_name, role, secret, username) values ('Чернышев','Чернышев','Чернышев','ADMIN','$2a$10$2ed6fBZO99N9pT1127Z7D.oKgXFl8JJ0l/SOyLx0SSB.bKQ7jIq3C','Chern')

-- create table public.exhibit
-- (
--     id   integer generated by default as identity
--         primary key,
--     name varchar(256) not null
-- );
--
-- alter table public.exhibit
--     owner to museum;
--
-- create table public.exhibit_description
-- (
--     id          integer generated by default as identity
--         primary key,
--     exhibit_id  integer      not null
--         constraint exhibit_fk
--             references public.exhibit,
--     description varchar(255) not null
-- );
--
-- alter table public.exhibit_description
--     owner to museum;
--
-- create table public.exhibition
-- (
--     id          integer generated by default as identity
--         primary key,
--     date_from   timestamp(6) not null,
--     date_to     timestamp(6) not null,
--     description text         not null,
--     name        varchar(256) not null
-- );
--
-- alter table public.exhibition
--     owner to museum;
--
-- create table public.shelving
-- (
--     id            integer generated by default as identity
--         primary key,
--     number        integer     not null,
--     type          varchar(16) not null,
--     exhibition_id integer
--         constraint exhibition_foreign_key
--             references public.exhibition,
--     room_id       integer
-- );
--
-- alter table public.shelving
--     owner to museum;
--
-- create table public.shelf
-- (
--     id          integer generated by default as identity
--         primary key,
--     number      integer not null,
--     shelving_id integer not null
--         constraint shelving_foreign_key
--             references public.shelving
-- );
--
-- alter table public.shelf
--     owner to museum;
--
-- create table public.exhibition_exhibit
-- (
--     id             integer generated by default as identity
--         primary key,
--     description_id integer not null
--         constraint description_fk
--             references public.exhibit_description,
--     exhibit_id     integer not null
--         constraint exhibit_fk
--             references public.exhibit,
--     exhibition_id  integer not null
--         constraint exhibition_fk
--             references public.exhibition,
--     shelf_id       integer not null
--         constraint shelf_fk
--             references public.shelf
-- );
--
-- alter table public.exhibition_exhibit
--     owner to museum;
--
-- create table public."user"
-- (
--     id          integer generated by default as identity
--         constraint pk_user
--             primary key,
--     name        varchar(64) not null,
--     middle_name varchar(64),
--     last_name   varchar(64) not null,
--     role        varchar(256),
--     secret      text        not null,
--     username    varchar(128) default 'user'::character varying
-- );
--
-- alter table public."user"
--     owner to museum;
--
-- create table public.room
-- (
--     id     integer generated by default as identity
--         primary key,
--     number integer not null
-- );
--
-- alter table public.room
--     owner to museum;
--
-- create table public.exhibition_room
-- (
--     id            integer generated by default as identity
--         primary key,
--     exhibition_id integer
--         constraint exhibition_foreign_key
--             references public.exhibition,
--     room_id       integer
--         constraint room_foreign_key
--             references public.room
-- );
--
-- alter table public.exhibition_room
--     owner to museum;

