create sequence public.shelfs_number_seq
    as integer;

alter sequence public.shelfs_number_seq owner to museum;

create sequence public.exhibition_exhibit_seq
    increment by 50;

alter sequence public.exhibition_exhibit_seq owner to museum;

create sequence public.exhibition_seq
    increment by 50;

alter sequence public.exhibition_seq owner to museum;

create sequence public.shelf_seq
    increment by 50;

alter sequence public.shelf_seq owner to museum;

create sequence public.shelving_seq
    increment by 50;

alter sequence public.shelving_seq owner to museum;

create sequence public.storages_seq
    increment by 50;

alter sequence public.storages_seq owner to museum;

create table public.users
(
    id          integer generated always as identity
        constraint user_pkey
            primary key,
    name        varchar(64)  not null,
    middle_name varchar(64),
    last_name   varchar(64)  not null,
    updated_at  timestamp(6),
    deleted_at  timestamp(6),
    created_at  timestamp(6) default CURRENT_TIMESTAMP,
    role        varchar(256) not null,
    secret      varchar(256) not null,
    username    varchar(128)
);

alter table public.users
    owner to museum;

create table public.exhibitions
(
    id          integer generated always as identity
        constraint exhibitions_pk
            primary key,
    name        varchar(256) not null,
    description text         not null,
    date_from   date         not null,
    date_to     date         not null,
    creator_id  integer
        constraint user_fk
            references public.users
);

alter table public.exhibitions
    owner to museum;

create table public.storages
(
    id      integer generated always as identity
        constraint storages_pk
            primary key,
    address text not null
);

alter table public.storages
    owner to museum;

create table public.rooms
(
    id         integer generated always as identity
        constraint rooms_pk
            primary key,
    number     integer not null,
    storage_id integer not null
        constraint rooms_storages_id_fk
            references public.storages
);

alter table public.rooms
    owner to museum;

create table public.shelvings
(
    id            integer generated always as identity
        constraint shelvings_pk
            primary key,
    number        serial,
    exhibition_id integer
        constraint exhibition_fk
            references public.exhibitions,
    type          varchar(16) not null,
    room_id       integer     not null
        constraint room_fk
            references public.rooms
);

alter table public.shelvings
    owner to museum;

create table public.shelfs
(
    id          integer generated always as identity
        constraint shelfs_pk
            primary key,
    number      integer not null,
    shelving_id integer not null
        constraint shelving_fk
            references public.shelvings
);

alter table public.shelfs
    owner to museum;

alter sequence public.shelfs_number_seq owned by public.shelfs.number;

create table public.exhibits
(
    id               integer generated always as identity
        constraint exhibits_pk
            primary key,
    packaging_type   varchar(64),
    storage_shelf_id integer      not null
        constraint exhibits_shelfs_id_fk
            references public.shelfs,
    name             varchar(256) not null
);

alter table public.exhibits
    owner to museum;

create table public.exhibition
(
    id          integer generated by default as identity
        primary key,
    date_from   timestamp(6) not null,
    date_to     timestamp(6) not null,
    description text         not null,
    name        varchar(256) not null
);

alter table public.exhibition
    owner to museum;

create table public.shelving
(
    id            integer     not null
        primary key,
    number        integer     not null,
    type          varchar(16) not null,
    exhibition_id integer
        constraint fkh3rue280m6lmi6i8vo51cpxid
            references public.exhibition,
    room_id       integer     not null
        constraint fkesk8o957c9b6s0c9xctb8a0vv
            references public.rooms
);

alter table public.shelving
    owner to museum;

create table public.role
(
    id   integer generated by default as identity
        primary key,
    role smallint
        constraint role_role_check
            check ((role >= 0) AND (role <= 1))
);

alter table public.role
    owner to museum;

create table public.shelf
(
    id          integer generated by default as identity
        primary key,
    number      integer default nextval('shelfs_number_seq'::regclass) not null,
    shelving_id integer                                                not null
        constraint fkmfum4qohpj3o7ijeh28fu7awg
            references public.shelving
);

alter table public.shelf
    owner to museum;

create table public.exhibit
(
    id               integer generated by default as identity
        primary key,
    name             varchar(256) not null,
    packaging_type   varchar(64),
    storage_shelf_id integer      not null
        constraint fk33j75ttp8msukvxvjcclk1g6v
            references public.shelf
);

alter table public.exhibit
    owner to museum;

create table public.exhibit_description
(
    id          integer generated always as identity
        constraint exhibit_description_pk
            primary key,
    description text    not null,
    exhibit_id  integer not null
        constraint exhibit_description_exhibits_id_fk
            references public.exhibits
        constraint fkbful2dheefwvugsts2p1d9luj
            references public.exhibit
);

alter table public.exhibit_description
    owner to museum;

create table public.exhibition_exhibit
(
    id             integer generated always as identity
        constraint exhibition_exhibit_pk
            primary key,
    exhibit_id     integer not null
        constraint exhibition_exhibit_exhibits_id_fk
            references public.exhibits
        constraint fkap3tjj73yctux3j9lu2m224ga
            references public.exhibit,
    shelf_id       integer not null
        constraint exhibition_exhibit_shelfs_id_fk
            references public.shelfs
        constraint fkhj6r43j342wtmqerapkjgm1hw
            references public.shelf,
    exhibition_id  integer not null
        constraint exhibition_exhibit_exhibitions_id_fk
            references public.exhibitions
        constraint fkbuyyrjkj4r2f6tgicmv8a4xw9
            references public.exhibition,
    description_id integer not null
        constraint exhibition_exhibit_exhibit_description_id_fk
            references public.exhibit_description
);

alter table public.exhibition_exhibit
    owner to museum;



alter table public.exhibition_exhibit
    owner to museum;

INSERT INTO users (name, middle_name, last_name,role, secret, username) values ('Александр', 'Викторович', 'Чернышев', 'ADMIN', '$2a$10$Cv3cK9p7czKP.flPHn5PGOChsKE96osAQ.n3NtzcYI.3TADuJb4pS', 'ChernyshevAV')