create table public.exhibit
(
    id   integer generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table public.exhibit
    owner to museum;

create table public.exhibit_description
(
    id          integer generated by default as identity
        primary key,
    exhibit_id  integer      not null
        constraint exhibit_fk
            references public.exhibit,
    description varchar(255) not null
);

alter table public.exhibit_description
    owner to museum;

create table public.exhibition
(
    id          integer generated by default as identity
        primary key,
    date_from   timestamp(6) not null,
    date_to     timestamp(6) not null,
    description varchar(255) not null,
    name        varchar(255) not null
);

alter table public.exhibition
    owner to museum;

create table public."user"
(
    id          integer generated by default as identity
        constraint pk_user
            primary key,
    name        varchar(64) not null,
    middle_name varchar(64),
    last_name   varchar(64) not null,
    role        varchar(256),
    secret      text        not null,
    username    varchar(128)
        constraint user_pk
            unique
);

alter table public."user"
    owner to museum;

create table public.room
(
    id     integer generated by default as identity
        primary key,
    number integer not null
);

alter table public.room
    owner to museum;

create table public.shelving
(
    id          integer generated by default as identity
        primary key,
    number      integer not null,
    room_id     integer
        constraint room_fk
            references public.room,
    description varchar(255)
);

alter table public.shelving
    owner to museum;

create table public.shelf
(
    id          integer generated by default as identity
        primary key,
    number      integer not null,
    shelving_id integer not null
        constraint shelving_foreign_key
            references public.shelving,
    description varchar(255)
);

alter table public.shelf
    owner to museum;

create table public.exhibition_exhibit
(
    id             integer generated by default as identity
        primary key,
    description_id integer not null
        constraint description_fk
            references public.exhibit_description,
    exhibit_id     integer not null
        constraint exhibit_fk
            references public.exhibit,
    exhibition_id  integer not null
        constraint exhibition_fk
            references public.exhibition,
    shelf_id       integer
        constraint shelf_fk
            references public.shelf,
    room_id        integer
        constraint exhibition_exhibit_room_id_fk
            references public.room
);

alter table public.exhibition_exhibit
    owner to museum;

create table public.exhibition_room
(
    id            integer generated by default as identity
        primary key,
    exhibition_id integer
        constraint exhibition_foreign_key
            references public.exhibition,
    room_id       integer
        constraint room_foreign_key
            references public.room
);

alter table public.exhibition_room
    owner to museum;


INSERT INTO "user" (name, middle_name, last_name, role, secret, username) VALUES ('А', 'В', 'Чернышев', 'ADMIN', '$2a$10$lmM50WjmyxFswT4eSpCK..NVe4UE9Ubng0pu3jk1snBPl3bphKlDq', 'ChernyshevAV')